apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: rohit19aug/shoppingcart
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
